extra_css:
  - "stylesheets/extra.css"
extra_javascript:
  - "javascripts/mathjax.js"
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
nav:
  - "Installation": "installation.md"
  - "Tutorials": "tutorials.md"
  - "Reference":
    - "beignet":
      - "Geometry":
          - "Transformations":
              - "Euler angle": "reference/operators/geometry/transformations/euler-angle.md"
              - "Quaternion": "reference/operators/geometry/transformations/quaternion.md"
              - "Rotation matrix": "reference/operators/geometry/transformations/rotation-matrix.md"
              - "Rotation vector": "reference/operators/geometry/transformations/rotation-vector.md"
              - "Transform": "reference/operators/geometry/transformations/transform.md"
              - "Translation": "reference/operators/geometry/transformations/translation.md"
      - "Integral transforms": "reference/operators/integral-transforms.md"
      - "Interatomic potentials": "reference/operators/interatomic-potentials.md"
      - "Numerical methods":
          - "Numerical integration": "reference/operators/numerical-methods/numerical-integration.md"
      - "Special functions":
          - "Dawson and Fresnel integrals": "reference/operators/special-functions/dawson-and-fresnel-integrals.md"
          - "Error and related functions": "reference/operators/special-functions/error-and-related-functions.md"
          - "Orthogonal polynomials":
              - "Polynomial": "reference/operators/special-functions/orthogonal-polynomials/polynomial.md"
              - "Chebyshev polynomial": "reference/operators/special-functions/orthogonal-polynomials/chebyshev-polynomial.md"
              - "Physicists’ Hermite polynomial": "reference/operators/special-functions/orthogonal-polynomials/physicists-hermite-polynomial.md"
              - "Probabilists’ Hermite polynomial": "reference/operators/special-functions/orthogonal-polynomials/probabilists-hermite-polynomial.md"
              - "Laguerre polynomial": "reference/operators/special-functions/orthogonal-polynomials/laguerre-polynomial.md"
              - "Legendre polynomial": "reference/operators/special-functions/orthogonal-polynomials/legendre-polynomial.md"
      - "Thermodynamics": "reference/operators/thermodynamics.md"
    - "beignet.datasets":
        - "General-purpose": "reference/datasets/general-purpose.md"
        - "Generation":
          - "Geometry":
            - "Transformations": "reference/datasets/generation/geometry/transformations.md"
          - "Molecule": "reference/datasets/generation/molecule.md"
          - "Protein":
            - "Protein sequence": "reference/datasets/generation/protein/protein-sequence.md"
            - "Protein structure": "reference/datasets/generation/protein/protein-structure.md"
          - "Reaction": "reference/datasets/generation/reaction.md"
          - "Retrosynthesis": "reference/datasets/generation/retrosynthesis.md"
        - "Prediction":
          - "Antibody affinity": "reference/datasets/prediction/antibody-affinity.md"
          - "Catalyst": "reference/datasets/prediction/catalyst.md"
          - "Drug interaction": "reference/datasets/prediction/drug-interaction.md"
          - "Drug intolerance": "reference/datasets/prediction/drug-intolerance.md"
          - "Epitope": "reference/datasets/prediction/epitope.md"
          - "Gene-disease association": "reference/datasets/prediction/gene-disease-association.md"
          - "Pharmacokinetic property":
              - "Absorption": "reference/datasets/prediction/pharmacokinetic-property/absorption.md"
              - "Distribution": "reference/datasets/prediction/pharmacokinetic-property/distribution.md"
              - "Excretion": "reference/datasets/prediction/pharmacokinetic-property/excretion.md"
              - "Metabolism": "reference/datasets/prediction/pharmacokinetic-property/metabolism.md"
          - "Protein–protein interaction": "reference/datasets/prediction/protein-protein-interaction.md"
          - "Quantum mechanics": "reference/datasets/prediction/quantum-mechanics.md"
          - "Reaction": "reference/datasets/prediction/reaction.md"
          - "Toxicity": "reference/datasets/prediction/toxicity.md"
          - "Sequences": "reference/datasets/sequences.md"
    - "beignet.features":
        - "General-purpose": "reference/features/general-purpose.md"
        - "Geometry":
            - "Transformations": "reference/features/geometry/transformations.md"
    - "beignet.func":
        - "Molecular dynamics": "reference/func/molecular-dynamics.md"
    - "beignet.io": "reference/beignet.io.md"
    - "beignet.transforms":
        - "General-purpose": "reference/transforms/general-purpose.md"
plugins:
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: "numpy"
            separate_signature: true
            show_root_heading: true
            show_source: true
site_name: "Beignet"
theme:
  features:
    - "navigation.sections"
  name: "material"
