extra_css:
  - "stylesheets/extra.css"
extra_javascript:
  - "javascripts/mathjax.js"
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
nav:
  - "beignet":
    - "Geometry":
        - "Transformations":
            - "Euler Angle": "operators/geometry/transformations/euler-angle.md"
            - "Quaternion": "operators/geometry/transformations/quaternion.md"
            - "Rotation Matrix": "operators/geometry/transformations/rotation-matrix.md"
            - "Rotation Vector": "operators/geometry/transformations/rotation-vector.md"
            - "Transform": "operators/geometry/transformations/transform.md"
            - "Translation": "operators/geometry/transformations/translation.md"
    - "Integral Transforms": "operators/integral-transforms.md"
    - "Interatomic Potentials": "operators/interatomic-potentials.md"
    - "Numerical Methods":
        - "Numerical Integration": "operators/numerical-methods/numerical-integration.md"
    - "Special Functions":
        - "Dawson and Fresnel Integrals": "operators/special-functions/dawson-and-fresnel-integrals.md"
        - "Error and Related Functions": "operators/special-functions/error-and-related-functions.md"
        - "Orthogonal Polynomials":
            - "Polynomial": "operators/special-functions/orthogonal-polynomials/polynomial.md"
            - "Chebyshev Polynomial": "operators/special-functions/orthogonal-polynomials/chebyshev-polynomial.md"
            - "Physicists’ Hermite Polynomial": "operators/special-functions/orthogonal-polynomials/physicists-hermite-polynomial.md"
            - "Probabilists’ Hermite Polynomial": "operators/special-functions/orthogonal-polynomials/probabilists-hermite-polynomial.md"
            - "Laguerre Polynomial": "operators/special-functions/orthogonal-polynomials/laguerre-polynomial.md"
            - "Legendre Polynomial": "operators/special-functions/orthogonal-polynomials/legendre-polynomial.md"
    - "Thermodynamics": "operators/thermodynamics.md"
  - "beignet.datasets":
      - "Geometry":
          - "Transformations": "datasets/geometry/transformations.md"
      - "Protein Sequences": "datasets/protein-sequences.md"
      - "Sequences": "datasets/sequences.md"
  - "beignet.features":
      - "Geometry":
          - "Transformations": "features/geometry/transformations.md"
  - "beignet.func":
      - "Molecular Dynamics": "func/molecular-dynamics.md"
  - "beignet.io": "operators.io.md"
  - "beignet.transforms":
      - "General-purpose": "transforms/general-purpose.md"
plugins:
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: "numpy"
            separate_signature: true
            show_root_heading: true
            show_source: true
site_name: "Beignet"
theme:
  name: "material"