extra_css:
  - "stylesheets/extra.css"
extra_javascript:
  - "javascripts/mathjax.js"
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
nav:
  - "Installation": "installation.md"
  - "Tutorials": "tutorials.md"
  - "Reference":
    - "beignet":
      - "Geometry":
          - "Transformations":
              - "Euler Angle": "reference/operators/geometry/transformations/euler-angle.md"
              - "Quaternion": "reference/operators/geometry/transformations/quaternion.md"
              - "Rotation Matrix": "reference/operators/geometry/transformations/rotation-matrix.md"
              - "Rotation Vector": "reference/operators/geometry/transformations/rotation-vector.md"
              - "Transform": "reference/operators/geometry/transformations/transform.md"
              - "Translation": "reference/operators/geometry/transformations/translation.md"
      - "Integral Transforms": "reference/operators/integral-transforms.md"
      - "Interatomic Potentials": "reference/operators/interatomic-potentials.md"
      - "Numerical Methods":
          - "Numerical Integration": "reference/operators/numerical-methods/numerical-integration.md"
      - "Special Functions":
          - "Dawson and Fresnel Integrals": "reference/operators/special-functions/dawson-and-fresnel-integrals.md"
          - "Error and Related Functions": "reference/operators/special-functions/error-and-related-functions.md"
          - "Orthogonal Polynomials":
              - "Polynomial": "reference/operators/special-functions/orthogonal-polynomials/polynomial.md"
              - "Chebyshev Polynomial": "reference/operators/special-functions/orthogonal-polynomials/chebyshev-polynomial.md"
              - "Physicists’ Hermite Polynomial": "reference/operators/special-functions/orthogonal-polynomials/physicists-hermite-polynomial.md"
              - "Probabilists’ Hermite Polynomial": "reference/operators/special-functions/orthogonal-polynomials/probabilists-hermite-polynomial.md"
              - "Laguerre Polynomial": "reference/operators/special-functions/orthogonal-polynomials/laguerre-polynomial.md"
              - "Legendre Polynomial": "reference/operators/special-functions/orthogonal-polynomials/legendre-polynomial.md"
      - "Thermodynamics": "reference/reference/operators/thermodynamics.md"
    - "beignet.datasets":
        - "Geometry":
            - "Transformations": "reference/datasets/geometry/transformations.md"
        - "Protein Sequences": "reference/datasets/protein-sequences.md"
        - "Sequences": "reference/datasets/sequences.md"
    - "beignet.features":
        - "Geometry":
            - "Transformations": "reference/features/geometry/transformations.md"
    - "beignet.func":
        - "Molecular Dynamics": "reference/func/molecular-dynamics.md"
    - "beignet.io": "reference/operators.io.md"
    - "beignet.transforms":
        - "General-purpose": "reference/transforms/general-purpose.md"
plugins:
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: "numpy"
            separate_signature: true
            show_root_heading: true
            show_source: true
site_name: "Beignet"
theme:
  features:
    - "navigation.sections"
  name: "material"
