# cheb  : chebyshev_series
# herm  : physicists_hermite_series
# herme : probabilists_hermite_series
# lag   : laguerre_series
# leg   : legendre_series
# poly  : power_series

import torch.linalg

from .__as_series import _as_series
from .__c_series_to_z_series import _c_series_to_z_series
from .__div import _div
from .__evaluate import _evaluate
from .__fit import _fit
from .__flattened_vandermonde import _flattened_vandermonde
from .__from_roots import _from_roots
from .__get_domain import _get_domain
from .__map_domain import _map_domain
from .__map_parameters import _map_parameters
from .__nonzero import _nonzero
from .__normed_hermite_e_n import _normed_hermite_e_n
from .__normed_hermite_n import _normed_hermite_n
from .__nth_slice import _nth_slice
from .__pad_along_axis import _pad_along_axis
from .__pow import _pow
from .__trim_coefficients import _trim_coefficients
from .__trim_sequence import _trim_sequence
from .__vandermonde import _vandermonde
from .__z_series_mul import _z_series_mul
from .__z_series_to_c_series import _z_series_to_c_series
from ._cheb2poly import cheb2poly
from ._chebadd import chebadd
from ._chebcompanion import chebcompanion
from ._chebder import chebder
from ._chebdiv import chebdiv
from ._chebdomain import chebdomain
from ._chebfit import chebfit
from ._chebfromroots import chebfromroots
from ._chebgauss import chebgauss
from ._chebgrid2d import chebgrid2d
from ._chebgrid3d import chebgrid3d
from ._chebint import chebint
from ._chebinterpolate import chebinterpolate
from ._chebline import chebline
from ._chebmul import chebmul
from ._chebmulx import chebmulx
from ._chebone import chebone
from ._chebpow import chebpow
from ._chebpts1 import chebpts1
from ._chebpts2 import chebpts2
from ._chebroots import chebroots
from ._chebsub import chebsub
from ._chebtrim import chebtrim
from ._chebval import chebval
from ._chebval2d import chebval2d
from ._chebval3d import chebval3d
from ._chebvander import chebvander
from ._chebvander2d import chebvander2d
from ._chebvander3d import chebvander3d
from ._chebweight import chebweight
from ._chebx import chebx
from ._chebzero import chebzero
from ._herm2poly import herm2poly
from ._hermadd import hermadd
from ._hermcompanion import hermcompanion
from ._hermder import hermder
from ._hermdiv import hermdiv
from ._hermdomain import hermdomain
from ._herme2poly import herme2poly
from ._hermeadd import hermeadd
from ._hermecompanion import hermecompanion
from ._hermeder import hermeder
from ._hermediv import hermediv
from ._hermedomain import hermedomain
from ._hermefit import hermefit
from ._hermefromroots import hermefromroots
from ._hermegauss import hermegauss
from ._hermegrid2d import hermegrid2d
from ._hermegrid3d import hermegrid3d
from ._hermeint import hermeint
from ._hermeline import hermeline
from ._hermemul import hermemul
from ._hermemulx import hermemulx
from ._hermeone import hermeone
from ._hermepow import hermepow
from ._hermeroots import hermeroots
from ._hermesub import hermesub
from ._hermetrim import hermetrim
from ._hermeval import hermeval
from ._hermeval2d import hermeval2d
from ._hermeval3d import hermeval3d
from ._hermevander import hermevander
from ._hermevander2d import hermevander2d
from ._hermevander3d import hermevander3d
from ._hermeweight import hermeweight
from ._hermex import hermex
from ._hermezero import hermezero
from ._hermfit import hermfit
from ._hermfromroots import hermfromroots
from ._hermgauss import hermgauss
from ._hermgrid2d import hermgrid2d
from ._hermgrid3d import hermgrid3d
from ._hermint import hermint
from ._hermline import hermline
from ._hermmul import hermmul
from ._hermmulx import hermmulx
from ._hermone import hermone
from ._hermpow import hermpow
from ._hermroots import hermroots
from ._hermsub import hermsub
from ._hermtrim import hermtrim
from ._hermval import hermval
from ._hermval2d import hermval2d
from ._hermval3d import hermval3d
from ._hermvander import hermvander
from ._hermvander2d import hermvander2d
from ._hermvander3d import hermvander3d
from ._hermweight import hermweight
from ._hermx import hermx
from ._hermzero import hermzero
from ._lag2poly import lag2poly
from ._lagadd import lagadd
from ._lagcompanion import lagcompanion
from ._lagder import lagder
from ._lagdiv import lagdiv
from ._lagdomain import lagdomain
from ._lagfit import lagfit
from ._lagfromroots import lagfromroots
from ._laggauss import laggauss
from ._laggrid2d import laggrid2d
from ._laggrid3d import laggrid3d
from ._lagint import lagint
from ._lagline import lagline
from ._lagmul import lagmul
from ._lagmulx import lagmulx
from ._lagone import lagone
from ._lagpow import lagpow
from ._lagroots import lagroots
from ._lagsub import lagsub
from ._lagtrim import lagtrim
from ._lagval import lagval
from ._lagval2d import lagval2d
from ._lagval3d import lagval3d
from ._lagvander import lagvander
from ._lagvander2d import lagvander2d
from ._lagvander3d import lagvander3d
from ._lagweight import lagweight
from ._lagx import lagx
from ._lagzero import lagzero
from ._leg2poly import leg2poly
from ._legadd import legadd
from ._legcompanion import legcompanion
from ._legder import legder
from ._legdiv import legdiv
from ._legdomain import legdomain
from ._legfit import legfit
from ._legfromroots import legfromroots
from ._leggauss import leggauss
from ._leggrid2d import leggrid2d
from ._leggrid3d import leggrid3d
from ._legint import legint
from ._legline import legline
from ._legmul import legmul
from ._legmulx import legmulx
from ._legone import legone
from ._legpow import legpow
from ._legroots import legroots
from ._legsub import legsub
from ._legtrim import legtrim
from ._legval import legval
from ._legval2d import legval2d
from ._legval3d import legval3d
from ._legvander import legvander
from ._legvander2d import legvander2d
from ._legvander3d import legvander3d
from ._legweight import legweight
from ._legx import legx
from ._legzero import legzero
from ._poly2cheb import poly2cheb
from ._poly2herm import poly2herm
from ._poly2herme import poly2herme
from ._poly2lag import poly2lag
from ._poly2leg import poly2leg
from ._polyadd import polyadd
from ._polycompanion import polycompanion
from ._polyder import polyder
from ._polydiv import polydiv
from ._polydomain import polydomain
from ._polyfit import polyfit
from ._polyfromroots import polyfromroots
from ._polygrid2d import polygrid2d
from ._polygrid3d import polygrid3d
from ._polyint import polyint
from ._polyline import polyline
from ._polymul import polymul
from ._polymulx import polymulx
from ._polyone import polyone
from ._polypow import polypow
from ._polyroots import polyroots
from ._polysub import polysub
from ._polytrim import polytrim
from ._polyval import polyval
from ._polyval2d import polyval2d
from ._polyval3d import polyval3d
from ._polyvalfromroots import polyvalfromroots
from ._polyvander import polyvander
from ._polyvander2d import polyvander2d
from ._polyvander3d import polyvander3d
from ._polyx import polyx
from ._polyzero import polyzero

torch.set_default_dtype(torch.float64)

__all__ = []
