jobs:
  claude:
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: claude
        uses: anthropics/claude-code-action@beta
        with:
          additional_permissions: |
            actions: read
          allowed_tools: "Bash(uv sync),Bash(uv run pytest),Bash(uv run python)"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          label_trigger: "claude"
          model: "claude-opus-4-20250514"
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [ created ]
