jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
      - run: "python -m pip install --upgrade build"
      - run: "python -m build ."
      - uses: "actions/upload-artifact@v3"
        with:
          name: "python-package-distributions"
          path: "dist/"
  test:
    environment:
      name: "test.pypi.org"
      url: "https://test.pypi.org/project/beignet"
    needs:
      - "build"
    permissions:
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: "python-package-distributions"
          path: "dist/"
      - uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          repository-url: "https://test.pypi.org/legacy/"
  publish:
    environment:
      name: "pypi.org"
      url: "https://pypi.org/project/beignet"
    if: "startsWith(github.ref, 'refs/tags/')"
    needs:
      - "build"
    permissions:
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: "python-package-distributions"
          path: "dist/"
      - uses: "pypa/gh-action-pypi-publish@release/v1"
  release:
    needs:
      - "publish"
    permissions:
      contents: "write"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: "python-package-distributions"
          path: "dist/"
      - uses: "sigstore/gh-action-sigstore-python@v1.2.3"
        with:
          inputs: "./dist/*.tar.gz ./dist/*.whl"
      - env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: "gh release create '${{ github.ref_name }}' --notes '' --repo '${{ github.repository }}'"
      - env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: "gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'"
on: "push"
